### ISSUE TITLE
Lightfields not showing up

### ISSUE THREAD

**Issue by ultra-sonic** [tatsy/LightField#2]
Hi Tatsuya,

long time has passed but i finally found the time to test your code and for some reason i just get a black window. no errors anywhere. Can you double check if there is anything wrong?
RAM is filling up while assembling the single images and the image size in the viewer also changes to the correct size, but it's just black. I have a feeling it's the openGL part of the code that has a bug.

tested on Centos 7 and Ubuntu

cheers
Oliver

**Comment by tatsy** [comment]
Hi Oliver,

First, could you tell me the size of your images?
For my program, the size of image can be critical 
because some GPUs only accept the sizes of powers 2.
When I made a screen shot for README.md, I used 16 x 16 images with 256 x 256 size.

Tatsuya.

**Comment by ultra-sonic** [comment]
Hi Tatsuya,

power of 2 makes sense, because I used the following lightfields:
http://lightfield.stanford.edu/data/chess_lf/rectified.zip 1400x800
http://lightfield.stanford.edu/data/amethyst_lf/rectified.zip 768x1024

cheers
Oli

**Comment by tatsy** [comment]
Hi Oliver,

Sorry for late in responding.

For the first dataset, I am not really sure but it does not fit to my program because its size is not the power of two.

For the second dataset, the file name format was invalid.
For this dataset, each image is named like `out_%d_%d__%lf_%lf_.png`, but some of other datasets in Stanford's repository are named as `out_%d_%d_%lf_%ld.png`. The difference is au underscore before extension.

Now I fixed the program to accept the second dataset.

Thanks for your information.

Tatsuya.
